pipeline:
  name: simple_ci_pipeline
  identifier: simple_ci_pipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.account_level_github_connector
        repoName: harness_mission_4
        build: <+input>
  stages:
    - stage:
        name: Build Stage
        identifier: Build_Stage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.paul_build_farm_connector
              namespace: harness_delegate_ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.account_level_dockerhub_connector
                    image: bash
                    shell: Sh
                    command: sh run.sh
